app = "vizard"  # غيّر الاسم إلى اسم التطبيق الخاص بك على fly.io إذا لزم الأمر
primary_region = "cdg"  # باريس على سبيل المثال، يمكنك تغييره حسب موقع جمهورك

[build]
  dockerfile = "Dockerfile"  # تأكد من أن المسار صحيح لملف Dockerfile

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  restart_limit = 0
